name: DevotedPvP
authors: [TealNerd]
version: 1.0
main: com.biggestnerd.devotedpvp.DevotedPvP
commands:
  inv:
    description: "Save/load inventories."
    usage: "Usage: /inv save/load <inventory> or /inv clear."
    permission: pvp.use
  duel:
    description: Requests to duel someone
    usage: /duel <playername>
    permission: pvp.use
  queue:
    description: Queue for a ranked duel
    usage: /queue
    permission: pvp.use
  accept:
    description: Accept the last duel request
    usage: /accept
    permission: pvp.use
  forfeit:
    description: Forfeit a duel
    usage: /forfeit
    permisson: pvp.use
    aliases: [ff, surrender]
  elo:
    description: Check your elo
    usage: /elo
    permission: pvp.use
    aliases: [rank]
  wand:
    description: Gives a wand for saving structures
    usage: /wand
    permission: pvp.badmin
  structure:
    description: Command for creating structures
    usage: /structure name
    permission: pvp.badmin
  team:
    description: Change your team
    usage: /team <color>
    permission: pvp.use
  spectate:
    description: Spectate another player
    usage: /spectate <player>
    permission: pvp.use

permissions:
  pvp.use:
    description: "use inventory saving/loading."
    default: true
  pvp.badmin:
    description: "Admin crimes inc"
    default: op