name: DevotedPvP
authors: [TealNerd]
version: 1.0
main: com.biggestnerd.devotedpvp.DevotedPvP
commands:
  inv:
    description: "Save/load inventories."
    usage: "Usage: /inv save/load <inventory> or /inv clear."
    permission: pvp.use
  duel:
    description: Requests to duel someone
    usage: /duel <playername>
    permission: pvp.duel
  queue:
    description: Queue for a ranked duel
    usage: /queue
    permission: pvp.queue
  accept:
    description: Accept the last duel request
    usage: /accept
    permission: pvp.duel
  forfeit:
    description: Forfeit a duel
    usage: /forfeit
    permisson: pvp.use
    aliases: [ff, surrender]
  elo:
    description: Check your elo
    usage: /elo
    permission: pvp.use
    aliases: [rank]
  team:
    description: Change your team
    usage: /team <color>
    permission: pvp.use
  spectate:
    description: Spectate another player
    usage: /spectate <player>
    permission: pvp.use
  maps:
    description: Command for map stuff
    usage: /maps <list|blank> or /maps create <name>
    permission: pvp.badmin
permissions:
  pvp.use:
    description: "use inventory saving/loading."
    default: true
  pvp.duel:
    description: "allows players to duel"
    default: op 
  pvp.queue:
    description: "allows players to queue"
    default: op
  pvp.badmin:
    description: "Admin crimes inc"
    default: op