sql:
  hostname: 'localhost'
  port: 3306
  dbname: 'devotedpvp'
  username: 'root'
  password: ''
spawnworld: world
spawnbounds:
  minx: 100
  miny: 100
  minz: 100
  maxx: 300
  maxy: 200
  maxz: 300
deathmessages:
 - RIP in pieces